# AppVeyor Dashboard

image: Visual Studio 2017
  
skip_tags: true
  
init:
  - git config --global core.autocrlf input

configuration: Release

before_build:
  - appveyor-retry dotnet restore

after_build:
  - dotnet publish "%APPVEYOR_BUILD_FOLDER%\src\AppVeyorDashboard" --configuration %CONFIGURATION% --output "%APPVEYOR_BUILD_FOLDER%\artifacts\AppVeyorDashboard"
 
artifacts:
  - path: Artifacts\AppveyorDashboard
    name: AppVeyorDashboard
    type: zip

on_failure:
- ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"

for:
-
  branches:
    only:
    - master
  
  version: 0.1.5

  deploy:
    - provider: Environment
      name: AppVeyor Dashboard

-
  branches:
    except:
    - master
  
  version: 0.1.5.{build}-{branch}